defaultContentLanguage = "dv"
baseURL = "https://nahushal.com/"
languageCode = "dv"
title = "ނަހުޝަލް ބްލޮގް"
disableKinds = ["taxonomy", "term"]

[params]
  description = "ނަހުޝަލްގެ ބްލޮގް: ދިވެހި ބަހުން ލިޔެވޭ ލިޔުންތައް"
  substack = "https://substack.com/@ibrahimnahushal"

[outputs]
  home = ["HTML", "RSS"]
