defaultContentLanguage = "dv"
baseURL = "https://nahushal.com/"
languageCode = "dv"
title = "ނަހުޝަލް ބްލޮގް"
disableKinds = ["taxonomy", "term"]

[params]
  description = "ނަހުޝަލްގެ ބްލޮގް: ދިވެހި ބަހުން ލިޔެވޭ ލިޔުންތައް"
  substack = "https://substack.com/@ibrahimnahushal"
  ga4 = "G-5JMJJ24VM9"
[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menus.main]]
  name = "ލިޔުން"
  url = "/posts/"
  weight = 1
[[menus.main]]
  name = "ފޮތް"
  url = "/books/"
  weight = 2
[[menus.main]]
  name = "ގުޅާލުމަށް ނުވަތަ މަޝްވަރާކުރުމަށް"
  url = "/contact/"
  weight = 3

[[menus.main]]
  name = "English Articles"
  url = "https://substack.com/@ibrahimnahushal"
  weight = 4